// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void funcClick(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    
    if(code == LV_EVENT_CLICKED) {
        buttonState = !buttonState;
        if(buttonState) {
            lv_label_set_text(ui_lblClickMe, "ON");
            lv_obj_set_style_text_color(ui_lblClickMe, lv_color_hex(0x000000), 0); 
            lv_obj_set_style_bg_color(ui_btnClickMe, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
        } else {
            lv_label_set_text(ui_lblClickMe, "OFF");
            lv_obj_set_style_text_color(ui_lblClickMe, lv_color_hex(0xFFFFFF), 0); 
            lv_obj_set_style_bg_color(ui_btnClickMe, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
    }
}